Senzing/aws-cloudformation-ecs-poc-simple

- CHANGELOG.md
- README.md
- cloudformation.yaml
- docs/README.md
> Issue 3.dockter.3

- CHANGELOG.md
- README.md
- cloudformation.yaml
- docs/README.md
> Issue 3.dockter.4

- CHANGELOG.md
- README.md
- cloudformation.yaml
- docs/README.md
> Issue 3.dockter.5

- README.md
- docs/README.md
> #3 Update cloudformation.yaml URL

- CHANGELOG.md
- cloudformation.yaml
> Issue 9.ant.1

- README.md
- docs/README.md
> #9 Update URL

- CHANGELOG.md
- cloudformation.yaml
- docs/README.md
> Issue 14.dockter.1

- cloudformation.yaml
> #22  Added mounting of /var/opt/senzing to senzing/stream-producer

- CHANGELOG.md
> #22 Prepare for versioned release

- cloudformation.yaml
> #26  Fixed documentation

- CHANGELOG.md
- cloudformation.yaml
> #27 Added SENZING_SKIP_DATABASE_PERFORMANCE_TEST

- CHANGELOG.md
- cloudformation.yaml
> Issue 34.dockter.1

- CHANGELOG.md
- README.md
- cloudformation.yaml
- docs/README.md
> Issue 20.dockter.1

- CHANGELOG.md
- cloudformation.yaml
- utils/create-repository-example.sh
> Issue 37.dockter.1

- CHANGELOG.md
- README.md
- cloudformation.yaml
- docs/README.md
> Issue 39.dockter.1

- cloudformation.yaml
> #41  Added slow_start.duration_seconds

- cloudformation.yaml
> Issue 43.dockter.1

- CHANGELOG.md
- README.md
- cloudformation.yaml
> Issue 43.dockter.2

- cloudformation.yaml
> #46 Rearranged resource definitions

- CHANGELOG.md
- cloudformation.yaml
> #46 Working system

- CHANGELOG.md
> #46 Prepare for release

- cloudformation.yaml
> Change TRUTH-SET1 to CUSTOMER and TRUTH-SET2 to WATCHLIST

- CHANGELOG.md
- cloudformation.yaml
> Issue 53.dockter.1

- CHANGELOG.md
- README.md
- cloudformation.yaml
> Issue 55.dockter.1

- cloudformation.yaml
- docs/README.md
> Issue 57.dockter.1

- CHANGELOG.md
- README.md
- cloudformation.yaml
- docs/README.md
> Issue 57.dockter.2

- CHANGELOG.md
- cloudformation.yaml
> Issue 57.dockter.3

- CHANGELOG.md
- cloudformation.yaml
- docs/README.md
> Add redoer queue

- CHANGELOG.md
- cloudformation.yaml
> Issue 64.dockter.1

- CHANGELOG.md
- cloudformation.yaml
> Issue 66.dockter.1

- README.md
- cloudformation.yaml
> Issue 66.dockter.3

- CHANGELOG.md
- cloudformation.yaml
> #72 Increased Senzing API Server CPU/Memory

- CHANGELOG.md
- cloudformation.yaml
> #74 Add Ec2SecurityGroupLoadBalancerPrivate for Senzing API Server'

- CHANGELOG.md
- cloudformation.yaml
> #71 Added check for email address
